# -*- coding: utf-8 -*-
"""CXDMO 资讯站英文内容。按文章 id 提供 title/summary/body；按企业 id 提供 tagline/desc。"""

ARTICLES_EN = {
    "porton-h1-2026": {
        "title": "Porton Pharma 2026 Interim Results: Revenue RMB 1.79B, Up 10% YoY; Continuing-Operations Profit Surges 329%",
        "summary": "Excluding a RMB 330M impairment from terminating the Slovenia project, continuing-operations net profit reached RMB 92.3M, up ~329% YoY. Gross margin improved by nearly 5 ppts; CGT and New Molecules order intake grew 75% and 84% respectively.",
        "body": [
            "Chongqing Porton Pharmaceuticals (300363.SZ) has released its 2026 semi-annual report. In the first half, the company continued its \"high-value customers, high-value projects\" strategy, generating revenue of RMB 1.79B, up ~10% YoY (~14% at constant exchange rates).",
            "Net profit attributable to shareholders was -RMB 224M, mainly due to a RMB 330M asset impairment provision related to the termination of its Slovenia investment project. Excluding this one-off item, continuing-operations net profit was RMB 92.3M, up ~329% YoY, driven by scale effects on revenue and a gross margin recovery: H1 gross margin was ~32%, up nearly 5 ppts YoY, with overseas market margin at ~45%, up ~4 ppts.",
            "By segment, the small-molecule API business served 380+ global clients and added 43 new customers in H1. Signed project orders (excluding J-STAR) reached 572, including 110 new projects; 398 projects were delivered, with 123 in the commercialized stage. The company completed 3 process validation (PV) projects, with 25 ongoing — building a reserve for future commercial work.",
            "The cell & gene therapy (CGT) business stood out: new orders reached ~RMB 91.9M, up ~75% YoY, with overseas clients accounting for 38%. Subsidiary Porton Bio (Suzhou) completed its first cell-therapy PV project and obtained its first Drug Manufacturing License (C license) during the reporting period, formally extending its CGT CDMO services into the commercial stage.",
            "The New Molecules business also grew strongly, with new orders of ~RMB 77M, up ~84% YoY, including successful full-cycle delivery of a dual-payload ADC process development and GMP IND clinical supply project. Porton has started expanding high-potency lines at its Fengxian plant, expected to come online in Q1 2027.",
        ],
    },
    "wuxi-xdc-singapore-bcm3": {
        "title": "WuXi XDC's Singapore BCM3 Dual-Function Line Achieves GMP Release — First Overseas Capacity Milestone",
        "summary": "BCM3 offers 200–2,000 L antibody-intermediate batches and up to 2,000 L conjugated drug substance batches. From announcement to GMP release took only two and a half years, marking a new stage in the company's \"China + Singapore\" dual-site global capacity layout.",
        "body": [
            "On August 17, 2026, WuXi XDC (2268.HK), the global leading bioconjugate CRDMO, announced that BCM3 — the dual-function line for antibody intermediates and conjugated drug substance at its Singapore site — has successfully completed GMP release. This is the company's first overseas facility to pass GMP release, marking a new stage of its global capacity expansion.",
            "Designed around an efficient, flexible \"dual-function\" concept, BCM3 provides one-stop commercial manufacturing from antibody intermediates to conjugated drug substance: antibody-intermediate batches range from 200 L to 2,000 L, while conjugated drug substance batches reach up to 2,000 L — fully meeting commercial-scale demand under a strict quality control system. BCM3 will work in synergy with the BCM1 and BCM2 lines in Wuxi, materially lifting overall capacity.",
            "During construction, WuXi XDC combined its Wuxi plant-building experience with local Singapore conditions, overcoming multiple design and construction challenges in highly potent and highly toxic production areas. From the announcement in March 2024, to mechanical completion in June 2025, to GMP release — the entire journey took just two and a half years, another demonstration of \"WuXi speed\".",
            "CEO Dr. Li Jincai commented: \"The successful GMP release of BCM3, our first overseas manufacturing facility, is an important milestone in WuXi XDC's global footprint. Leveraging the 'China + Singapore' dual-site advantage, we will significantly enhance flexible delivery for diversified orders and provide solid capacity assurance for clients' commercial production.\"",
        ],
    },
    "wuxi-biologics-transcenta": {
        "title": "WuXi Biologics to Acquire Transcenta's Hangzhou Site for RMB 190M, Expanding DS & DP Capacity",
        "summary": "The 10,000+ sqm site offers process development, drug substance and drug product capabilities, with the deal expected to close in Q3 2026 — the latest move in WuXi's counter-cyclical capacity buying at domestic asset-price lows.",
        "body": [
            "On August 7, 2026, WuXi Biologics (2269.HK) announced an agreement with Transcenta Therapeutics to acquire its Hangzhou process development, drug substance and drug product manufacturing site, further strengthening integrated service capability to meet rapidly growing client demand. The transaction is expected to close in Q3 2026.",
            "According to Transcenta's concurrent announcement, the deal transfers the entire Hangzhou Just Biotherapeutics CDMO asset package for ~RMB 190M, paid in four installments tied to closing milestones. The book value of the assets is ~RMB 457M (including RMB 202M of goodwill); the transaction covers hardware, contracts and designated employees only — excluding the HiCB continuous processing and ExcelPro CHO IP. For WuXi Biologics, it is effectively a ready-made GMP plant at roughly a quarter of book value.",
            "The site spans more than 10,000 square meters with process development, drug substance and drug product capabilities. CEO Dr. Chris Chen said: \"This acquisition further enhances our end-to-end capability covering drug substance development and manufacturing and drug product. As project volume and commercial demand keep growing, we will continue responding to clients' diversified needs with high quality and efficiency.\"",
            "Industry observers note this is the latest in WuXi's 2026 M&A sequence: in January, WuXi XDC completed a ~HK$3.09B tender offer for over 60% of TOT Biopharma, securing 20,000+ L of integrated ADC commercial capacity at its Suzhou base. With domestic biotech funding cold and asset prices low, WuXi entities are using \"M&A + guaranteed orders\" to keep expanding their manufacturing networks.",
        ],
    },
    "industry-cdmo-two-paths": {
        "title": "Two Playbooks in Large-Molecule CDMO: WuXi Buys Capacity Counter-Cyclically While Lonza/Catalent Divest to Refocus",
        "summary": "In 2026, with domestic biotech funding cold and legacy Western CDMOs retreating, top players are moving in opposite directions — WuXi turning \"M&A + guaranteed orders\" into a capacity harvester, while Lonza and Catalent use \"divestment + refocusing\" as a margin-repair playbook.",
        "body": [
            "The 2026 large-molecule CDMO market shows a rare regional divergence: with domestic primary-market assets cheap, WuXi entities are acquiring ready-made GMP capacity and filling it with related-party orders; legacy Western CDMOs are divesting non-core assets and concentrating on high-margin businesses. Both, however, are betting on the same long-term logic — biopharma outsourcing penetration climbing toward 65%.",
            "WuXi's approach can be summarized as an \"acquire — integrate — feed guaranteed orders — ramp with small batches\" loop. In January 2026, WuXi XDC made a ~HK$3.09B cash tender offer for over 60% of TOT Biopharma (Dongyao), the core asset being an integrated antibody + ADC drug substance + drug product plant in Suzhou exceeding 20,000 L — precisely the commercial-grade capacity scarcest in ADC CDMO. After taking control, WuXi XDC signed a three-year stepped guaranteed CDMO agreement worth nearly RMB 770M in total for 2026–2028, while WuXi Biologics placed small batches to validate the quality system.",
            "August's Transcenta deal followed the same pattern: RMB 190M for a Hangzhou site with RMB 457M book value, buying hardware + contracts + designated staff only. Through this series of deals, WuXi Biologics' manufacturing capacity pool has grown to ~580,000 L. With 28 PPQ projects completed in 2025 (+75% YoY) and 34 planned for 2026, the company is expected to enter a concentrated commercial-approval release inflection from H2 2026 into 2027.",
            "Meanwhile, Lonza and Catalent are on a \"margin repair\" path: divesting inefficient capacity while focusing on advantaged modalities. Lonza delivered a standout H1 2026 for Advanced Synthesis — CER sales +27.7% and a 48.1% CORE EBITDA margin — while precisely adding to ADC-related assets in Visp and Stein. What shrinks is the perimeter; what grows is the direction.",
            "For industry watchers, both routes rest on the same conviction: biopharma outsourcing penetration has a decade or more of upside, and the window belongs to players with both capacity and the order conversion to fill it. China's CXDMO cost-and-speed edge, amplified by the M&A window, is reshaping the global large-molecule CDMO competitive landscape.",
        ],
    },
    "asymchem-h1-2026": {
        "title": "Asymchem H1 2026 (HK): Revenue RMB 3.19B, Up 20.1%; Peptide Capacity to Reach 69,000 L by Year-End",
        "summary": "H1 gross profit rose 26% to RMB 1.38B and net profit grew 23.7% to RMB 617M, completing a Q2 inflection after a weak Q1. Chemical macromolecule CDMO backlog keeps doubling; 52 clinical peptide programs include 19 obesity-related projects.",
        "body": [
            "Asymchem's H-share results (6821.HK), released on August 11, showed H1 2026 revenue of RMB 3.19B, up 20.1% YoY; gross profit of RMB 1.38B, up 26%; and net profit of RMB 617M, up 23.7%. Against a Q1 where A-share net profit fell 6.82% YoY, Q2 marked a clear turn from weakness to strength.",
            "The market responded strongly. On August 20, Asymchem's A-shares hit the daily limit at RMB 187.65, with a record single-day turnover of RMB 4.57B and market cap briefly topping RMB 65.8B — multiple all-time records. The entire pharma board rallied that day, with 38 pharma stocks hitting the limit — sparked by WuXi AppTec's better-than-expected interim report in early August.",
            "On fundamentals, Asymchem's emerging businesses are entering a harvest period: the chemical macromolecule CDMO segment exceeded RMB 1B revenue in 2025, doubling YoY, with backlog continuing to double in 2026. The company holds 52 clinical peptide programs — 19 obesity-related and 8 in late-stage trials — and plans to expand peptide solid-phase synthesis capacity from 45,000 L to 69,000 L by end-2026.",
            "Caveats remain: peptide commercial orders are long-cycle, with uneven revenue recognition, and the company's high overseas revenue mix exposes it to geopolitical and client-capex risks. Asymchem's A-share interim report is due August 25.",
        ],
    },
    "pharmaron-h1-2026": {
        "title": "Pharmaron H1 2026: Revenue RMB 7.60B, Up 17.92%; New Order Intake Grows Over 30%",
        "summary": "CDMO services new orders jumped over 50% with segment revenue of RMB 1.88B (+32.78%); the company guides 15–20% full-year revenue growth. Revenue from the global top-20 pharma clients surged 31.95%.",
        "body": [
            "Pharmaron (300759.SZ / 3759.HK) reported H1 2026 results on August 20: revenue of RMB 7.60B, up 17.92% YoY; net profit attributable of RMB 750M, up 6.96%; and adjusted non-IFRS net profit of RMB 909M, up 20.29%. Based on new-order and business trends, the company expects 15–20% full-year revenue growth.",
            "During the period, Pharmaron reorganized into three platforms: Laboratory Services, CDMO Services and Clinical Research Services. CDMO led the way: revenue of RMB 1.88B, up 32.78% YoY, with gross margin of 25.72%, up 2.57 ppts. Its small-molecule CDMO covers 782 molecules or intermediates, including 45 process-validation/commercial-stage and 51 Phase III projects.",
            "Laboratory Services delivered RMB 4.63B revenue (+13.72%, gross margin 40.89%), with biology accounting for over 60%; Clinical Research Services earned RMB 1.07B (+13.75%). Total new orders grew over 30% — CDMO services new orders up more than 50%, laboratory services up more than 20%.",
            "Client mix keeps improving: 470+ new clients were added, and revenue from the global top-20 pharma companies reached RMB 1.54B, up 31.95%, or 20.29% of revenue. By region, North America contributed RMB 4.68B (61.55%) while mainland China grew 41.93% to RMB 1.38B. Headcount reached 27,316, with 11 operating entities in the UK and US. The company also completed an H-share placement in January, netting ~RMB 1.19B.",
        ],
    },
    "industry-adc-race": {
        "title": "The ADC Capacity Race: Three Expansion Playbooks from WuXi XDC, Samsung Biologics and Lonza",
        "summary": "Small-molecule players extend into linker-payloads, biologics players extend from mAbs into conjugation, and large CDMOs fill gaps in drug product and fill-finish — different starting points, the same destination: integrated XDC. China's H1 2026 license-out value neared USD 100B.",
        "body": [
            "The ADC (antibody-drug conjugate) boom is moving from R&D to the production line. As ADCs evolve into XDCs — where the classic \"antibody + small-molecule payload\" no longer covers all needs — capabilities for oligonucleotides, peptides, protein degraders and novel payloads have become the focus of CDMO competition.",
            "Three distinct expansion logics are visible: small-molecule specialists extending into linker-payloads and conjugation; biologics players extending from mAbs into conjugation; and multi-platform CDMOs filling gaps in payload-linkers, drug product and fill-finish.",
            "WuXi XDC represents the vertical-integration route. In 2025 it posted revenue of RMB 5.94B (+46.7%) with a USD 1.49B backlog. Its planned Jiangyin payload-linker facility will have capacity equal to five times the current Wuxi base; the TOT Biopharma (Dongyao) acquisition added mAb, drug substance and drug product capability; the Hefei site adds peptide and oligonucleotide synthesis; and together with the Singapore site, a \"China + Singapore\" dual-supply system has taken shape.",
            "Samsung Biologics, a large-scale mAb specialist, has stood up a dedicated ADC facility — with up to 500 L conjugation reactors and containment systems targeting occupational exposure limits below 1 ng/m³ for HPAPI handling. Its ADC drug product line is slated for completion in Q1 2027 to build end-to-end ADC capability.",
            "Lonza runs arguably the most complete single-organization chain: antibody, linker, payload, conjugation and drug product — and in 2026 integrated the Synaffix platform, adding dual-payload ADC technology. A \"networked one-stop\" model is also emerging, where one platform coordinates project management across specialized suppliers. For China's CXDMOs, H1 2026 license-out deals reached USD 99.7–110B, and China now hosts 1,728 clinical trials versus 1,520 in the US — China has become a co-equal center of ADC innovation.",
        ],
    },
    "porton-bio-license-c": {
        "title": "Porton Bio Obtains Drug Manufacturing License (C), Extending CGT CDMO into the Commercial Stage",
        "summary": "Suzhou Porton Bio received the license from the Jiangsu MPDA, qualifying it for commercial CGT contract manufacturing. H1 CGT new orders grew ~75% YoY; lentiviral platform material localization exceeds 96%.",
        "body": [
            "Porton Pharma (300363.SZ) announced that its subsidiary Suzhou Porton Biopharma has obtained the Drug Manufacturing License (No. Su 20260010, classification code Cs, valid to July 26, 2031) from the Jiangsu Provincial Medical Products Administration. This is Porton Bio's first such license, qualifying it for commercial-stage contract manufacturing of cell and gene therapy (CGT) products — extending its CGT CDMO services from process development and clinical production into commercialization.",
            "The milestone follows rapid business growth: H1 2026 CGT new orders reached ~RMB 91.9M, up ~75% YoY, with overseas clients accounting for 38%. During the period, Porton Bio completed its first cell-therapy process validation project, supported a client's oncolytic-bacteria US-China dual IND filing, and helped a client win China's first lentiviral in vivo CAR-T IND approval.",
            "On supply chain, Porton Bio has achieved multi-source localization: cell-therapy platform materials are 80% domestic, the lentiviral platform over 96%, and the plasmid platform over 98%, materially improving resilience. On August 6, Porton Bio also formed a strategic partnership with Yeasen Biotechnology covering custom transfection reagent development and joint QC product validation — connecting core raw materials with CDMO services.",
            "Porton Pharma cautioned that commercial manufacturing will proceed according to client timelines, and the license is not expected to materially affect 2026 results. But as the CGT industry enters its commercialization phase, the CDMOs that secured their commercial \"ticket\" early are positioned to lead the next competitive round.",
        ],
    },
    "wuxi-apptec-h1-2026": {
        "title": "WuXi AppTec H1 2026: Revenue RMB 28.9B, Up 38.9%; Full-Year Guidance Raised Across the Board",
        "summary": "Adjusted non-IFRS net profit of RMB 11.57B, up 83.2% YoY; backlog of RMB 66.4B, up 25.2%; full-year revenue guidance raised to RMB 58.5–60.5B. Attributable net profit topped RMB 10B in H1 for the first time.",
        "body": [
            "On August 3, WuXi AppTec (603259.SH / 2359.HK) reported H1 2026 results: total revenue of RMB 28.90B, up 38.9% YoY; continuing-operations revenue up 48.0%; adjusted non-IFRS net profit of RMB 11.57B, up 83.2%, with net margin up 9.7 ppts to 40.0%; and attributable net profit of RMB 11.08B, up 29.4% — the first time H1 attributable profit has exceeded RMB 10B.",
            "As of end-June 2026, continuing-operations backlog stood at RMB 66.43B, up 25.2% YoY; adjusted operating cash flow was RMB 9.98B, up 41.3%. By segment, Chemistry business revenue was RMB 24.99B (+53.3%), still the core driver — small-molecule D&M (process R&D and manufacturing) revenue reached RMB 14.99B, up 72.7%; the TIDES business (oligonucleotides and peptides) earned RMB 7.26B, up 44.3%, with ~45% full-year growth expected. Testing business revenue was RMB 2.48B (+31.5%) and Biology RMB 1.39B (+11.2%).",
            "On the strength of these results, the company raised all its 2026 guidance: full-year revenue from RMB 51.3–53.0B to RMB 58.5–60.5B; continuing-operations revenue growth from 18–22% to 35–39%; capex from RMB 6.5–7.5B to RMB 7.5–8.5B (early-starting a new Changzhou base); and adjusted free cash flow from RMB 10.5–11.5B to RMB 13.5–14.5B.",
            "Chairman and CEO Dr. Ge Li commented: \"Thanks to the greater success of multiple client products, our unique CRDMO business model and excellent execution, revenue, profit and cash flow all grew strongly.\" He also addressed the US DoD 1260H listing: \"The erroneous designation lacks factual basis and legal support. We have taken legal action; the litigation is ongoing, and we are confident a fair judicial review will vindicate the facts.\"",
            "The same day, the company unveiled a 2026 A-share employee stock ownership plan covering up to 4,000 managers and core technical staff, granting up to 9.70M shares at RMB 103.08 per share from long-term incentive funds of up to RMB 1B, with vesting tied to 2026 revenue targets. An interim dividend of RMB 5.1 per 10 shares (RMB 1.51B total) was also declared. On ESG, the company retained its MSCI AAA rating and was included in the FTSE4Good Index Series for the fourth consecutive year.",
        ],
    },
    "samsung-biologics-q2-2026": {
        "title": "Samsung Biologics Q2 2026: Revenue KRW 1,321B, Up 30%; Cumulative Contract Value Reaches USD 21.6B",
        "summary": "Plants 1–4 ran at full utilization with operating profit of KRW 586.4B and an operating margin of 44.4%; Plant 5 PPQ batches are ramping, and the company expects to hit the upper end of its 15–20% full-year revenue growth guidance.",
        "body": [
            "On July 23, Samsung Biologics (207940.KS) reported Q2 2026 results: revenue of KRW 1,321B (+30.2% YoY), operating profit of KRW 586.4B, and EBITDA of KRW 698.5B. First-half revenue totaled KRW 2,578B with operating profit of KRW 1,167B. Cumulative contract value reached USD 21.6B, reflecting sustained global demand for its integrated development and manufacturing services.",
            "Performance was driven by favorable FX and full utilization of Plants 1–4 at Songdo's Bio Campus I. Despite batch disruptions from a May union strike, the company still posted a 44.4% operating margin. Plant 5's process performance qualification (PPQ) batches continue to ramp and are expected to lift H2 revenue. Samsung Biologics expects to reach the upper end of its 15–20% full-year revenue growth guidance.",
            "Global expansion continues: following the March completion of the GSK Rockville acquisition — its first US manufacturing presence — the site is being integrated into the global network; a Netherlands sales office opens in Q3, completing coverage across the US (New Jersey), Japan (Tokyo) and Europe.",
            "On innovation, the Life Science Fund — jointly created by Samsung Biologics, Samsung Bioepis and Samsung C&T — invested in Cartography Biosciences in May and committed an additional KRW 200B to create a third fund in June. The company is advancing proprietary platform technologies and expanding into ADC, peptides, AAV and other modalities. On ESG, it was included in the Dow Jones Best-in-Class Indices for the fifth consecutive year.",
        ],
    },
    "lonza-h1-2026": {
        "title": "Lonza Delivers Strong H1 2026, Upgrades Full-Year CORE EBITDA Margin Guidance to 33–34%",
        "summary": "H1 sales of CHF 3.4B with a CORE EBITDA margin of 34.8%; Advanced Synthesis posted CER sales growth of +27.7% with a 48.1% margin. The Visp large-scale mammalian facility began commercial operations, and a new ADC fill-finish line is being added in Stein.",
        "body": [
            "On July 22, Lonza reported H1 2026 results: sales of CHF 3.4B and a CORE EBITDA margin of 34.8%. On the strength of all three business platforms, the company upgraded its 2026 CORE EBITDA margin guidance from \"above 32%\" to 33–34%, and confirmed CER sales growth guidance of 11–12%.",
            "By platform: Integrated Biologics reported CER sales growth of +10.0% with a flat CORE EBITDA margin of 36.0%; the large-scale mammalian drug substance facility in Visp began commercial operations on schedule in H1. Lonza also expanded a strategic long-term collaboration with a leading US biopharmaceutical company, providing clinical and commercial biologics manufacturing across all of its US commercial-scale mammalian sites.",
            "The standout was Advanced Synthesis: CER sales up 27.7% YoY, with the CORE EBITDA margin jumping 6.8 ppts to 48.1%, on strong small-molecules and bioconjugates demand, higher asset utilization and a favorable mix. Management cautioned that H2 growth will moderate against a significantly higher prior-year base.",
            "On capacity investments, H1 capex was CHF 0.5B (15.7% of sales). The company simultaneously announced a new commercial-scale multi-purpose ADC filling line in Stein (operational 2030), supported by a long-term collaboration with a major pharmaceutical company for clinical and commercial ADC supply; the large-scale drug product facility's scope was extended to high-value small molecules with operations now expected in 2028. This follows June's announcement of expanded HPAPI and payload-linker capacity in Visp. At Vacaville (acquired from Roche in 2024), the first non-Roche product has been tech-transferred with first GMP batches produced.",
        ],
    },
    "wuxi-biologics-1000th-molecule": {
        "title": "WuXi Biologics Reaches 1,000th Integrated Project Milestone, Powering Earendil Labs' Trispecific Antibody",
        "summary": "From 982 integrated projects at end-April 2026 to 1,000 by July, the project pool keeps expanding — complex molecules now exceed 50% of the portfolio, with bispecific/multispecific antibodies as a key growth engine.",
        "body": [
            "On July 20, 2026, WuXi Biologics (2269.HK) announced its 1,000th integrated project milestone — the latest being an innovative trispecific antibody for Earendil Labs. As a global leading large-molecule CRDMO, the milestone marks a new level for its open, integrated biotherapeutics enabling platform.",
            "As of end-April 2026, WuXi Biologics' integrated portfolio stood at 982 projects, including 78 Phase III and 25 commercial manufacturing projects, with complex molecules accounting for more than 50% of the total. A little over two months later, the count crossed 1,000.",
            "New molecule types are becoming the core growth engine: of the 69 new projects signed by April 30, 2026, bispecific/multispecific antibody signings grew more than 50% YoY. Sell-side analysts note WuXi Biologics' global competitiveness in bispecifics, ADCs and other emerging fields is stronger than peers', with stickier R-to-D-to-M conversion and higher barriers.",
            "Other recent milestones include: MFG8 drug substance plant passing US FDA pre-license inspection (PLI) for a potential blockbuster autoimmune therapy; ANVISA (Brazil) GMP certification; the 25th drug substance plant completing its first GMP batches with zero deviations; and the Suzhou testing center's fourth EMA GMP certification supporting 19 commercial products into Europe. The company's 2026 capex is expected at ~RMB 7.1B (including RMB 1.5B deferred from 2025), up 92% YoY, for domestic expansion plus Singapore and US capacity build-out.",
        ],
    },
    "lonza-visp-hpapi": {
        "title": "Lonza Expands HPAPI & Payload-Linker Capacity in Visp, Strengthening Its Integrated ADC Position",
        "summary": "The new capacity, inside an existing GMP facility, is expected to be operational in 2028 and will support both clinical and commercial programs, complementing Lonza's antibody, conjugation and fill-finish ecosystem in Visp and Stein.",
        "body": [
            "On June 30, Lonza announced plans to enhance its drug-linker center of excellence and expand payload-linker manufacturing capacity at its Visp site (CH), supporting the fast-growing ADC market. The expansion will establish new commercial-scale capabilities for highly potent APIs (HPAPI) and ADC payload-linkers, reinforcing Lonza's position as the leading fully-integrated CDMO partner in the ADC space.",
            "Built within an existing GMP facility, the new capacity adds payload-linker production and purification alongside dedicated analytical and process development laboratories. The facility is designed for multipurpose use and scale-out, enabling flexible production of a broad range of payload-linker molecules with the option to add further suites as demand grows. It is expected to be operational in 2028, supporting both clinical and commercial programs.",
            "The new capacity is closely connected to Lonza's broader integrated ADC ecosystem in Visp — including monoclonal antibody manufacture and conjugation, plus drug product capabilities in Visp and Stein — complemented by QC capacity able to handle highly potent payload-linkers.",
            "This is one of Lonza's series of 2026 ADC moves: in February, the company fully integrated the ADC technology platform obtained via the Synaffix acquisition (GlycoConnect conjugation, HydraSpace spacers and the toxSYN linker-payload portfolio) into Advanced Synthesis and added dual-payload ADC technology; the Oss (NL) site expanded labs to cover antibody-oligonucleotide conjugates, targeted lipid nanoparticles and other emerging modalities. Christian Seufert, Head of Advanced Synthesis, said: \"The rapid growth of the ADC market is driving demand for highly complex payload-linkers; Lonza remains committed to investing in and further developing our integrated ADC offering.\"",
        ],
    },
    "samsung-biologics-polypeptide": {
        "title": "Samsung Biologics Launches $1.8B Tender Offer for PolyPeptide, Doubling Down on Peptide Therapeutics",
        "summary": "The all-cash public tender offer for the Swiss peptide CDMO is expected to close by end-2026, adding six cGMP plants across Belgium, France, India, Sweden and the US — a major step in Samsung's multi-modality strategy.",
        "body": [
            "Samsung Biologics has announced an all-cash public tender offer of approximately USD 1.8B for PolyPeptide Group AG, the Switzerland-headquartered peptide CDMO, with completion expected toward the end of 2026. It is the company's second major acquisition of the year, following the GSK Rockville plant purchase completed in March.",
            "PolyPeptide operates six cGMP manufacturing facilities in Belgium, France, India, Sweden and the US. Through the deal, Samsung Biologics' network will extend across the US, Europe and India, with capabilities broadening from antibodies and ADCs into peptide therapeutics — one of the fastest-growing biopharma segments, highly relevant to oncology and emerging indications.",
            "The transaction is a key step in Samsung Biologics' multi-modality strategy. The company has previously said it is studying peptides, AAV and other next-generation modalities. Combined with its dedicated ADC facility, the Samsung Organoid CRO offering and Life Science Fund ecosystem investments, Samsung Biologics is evolving from \"the world's largest mAb CDMO\" into a multi-modality platform bio-service provider.",
            "For the industry, the deal underscores the peptide boom: the commercial explosion of GLP-1 weight-loss and metabolic drugs has made upstream peptide CDMO capacity a scarce resource. Notably, China's Asymchem is also expanding peptide solid-phase synthesis capacity from 45,000 L to 69,000 L — Korean and Chinese CDMO giants are landing on the peptide board almost simultaneously.",
        ],
    },
    "samsung-biologics-rockville": {
        "title": "Samsung Biologics Completes Acquisition of GSK's Rockville Plant, Total Capacity Rises to 845,000 L",
        "summary": "The deal adds 60,000 L of drug substance capacity (2×20,000 L + 2×10,000 L bioreactors) and establishes the company's first US manufacturing presence. Once Songdo Bio Campus II is complete, total capacity will reach 1.385M L.",
        "body": [
            "On March 31, Samsung Biologics announced the completion of its acquisition of a GSK manufacturing facility in Rockville, Maryland — the company's first US production site. The site comprises two cGMP plants with a combined 60,000 L of drug substance capacity (two 20,000 L and two 10,000 L bioreactors), supporting clinical and commercial biologics at multiple scales. With the addition, Samsung Biologics' total global capacity rises to 845,000 L.",
            "Under the agreement, Samsung Biologics will continue supplying the products previously manufactured at the site to GSK while transitioning the site to additional contract manufacturing, with further investments planned to expand capacity and upgrade technologies. More than 500 site employees joined the company. CEO John Rim said: \"The Rockville site strengthens our ability to operate a geographically diversified manufacturing network and offer flexible production options to global clients.\"",
            "In Korea, the Songdo expansion continues: Plant 5 (180,000 L, fully automated) came online in 2025 with PPQ batches ramping, and a Plant 6 go/no-go decision is expected this year (adding another 180,000 L). Bio Campus II — Plants 5 through 8 — is slated for completion by 2032, bringing Songdo to 1.325M L and total capacity to 1.385M L. Samsung is also partnering with Eli Lilly on a Lilly Gateway Labs site at Bio Campus II — a 125,000 sq ft facility due in 2027 that will host up to 30 biotech companies.",
            "Notably, management dismisses antibody overcapacity concerns: \"Beyond monoclonals, multispecific antibodies are being actively developed, and the market is expanding across immune diseases, cancer, CNS and even anti-aging,\" the company said, arguing demand will keep growing.",
        ],
    },
    "wuxi-xdc-2025-results": {
        "title": "WuXi XDC FY2025 Results: Revenue RMB 5.94B, Up 46.7%; Backlog Reaches USD 1.49B",
        "summary": "643 cumulative clients, 252 integrated CMC programs (226 integrated ADC projects), 18+ PPQ projects; the planned Jiangyin payload-linker facility will have capacity equal to five times the current Wuxi base.",
        "body": [
            "WuXi XDC's (2268.HK) 2025 results showed full-year revenue of RMB 5.94B, up 46.7% YoY, consolidating its global leadership in the bioconjugate CRDMO market.",
            "Operating metrics grew across the board: 643 cumulative clients; 252 integrated CMC (iCMC) programs, including 226 integrated ADC projects; more than 18 process performance qualification (PPQ) projects; and a backlog of USD 1.49B. The company has enabled over 100 successful IND filings by clients worldwide.",
            "On capacity, the company plans a new payload-linker facility in Jiangyin with planned capacity equal to five times the current Wuxi base, covering dual-payloads, AOCs (antibody-oligonucleotide conjugates) and late-stage PPQ batches. The TOT Biopharma (Dongyao) acquisition added mAb, drug substance and drug product capabilities, while the Hefei site adds peptide and oligonucleotide synthesis. Combined with the Singapore site, a \"China + Singapore\" dual-supply system is taking shape.",
            "On the demand side, XDC momentum keeps building: the first two months of 2026 saw 25 global XDC financing events versus 18 in the same period of 2025, with XDC BD deal counts stable and upfront payments up sharply. Analysts see WuXi XDC — with both technical strength and integrated delivery — as well positioned to benefit and gain share.",
        ],
    },
    "wuxi-apptec-steroid-rcs": {
        "title": "From Doubt to Trust: WuXi AppTec RCS Cuts Steroid Route from 7 Steps to 3, Doubles Yield",
        "summary": "WuXi AppTec's Research Chemistry Services (RCS) shortened a client's steroid synthesis from 7 steps to 3 while doubling yield; two years later, when kg-scale failed, RCS validated across four scales and introduced continuous precipitation, cutting 100g production from two weeks to four days — winning deep collaboration.",
        "body": [
            "The client's original route had seven steps, low yield, and severe regioselectivity issues — multiple reactive sites on the steroid molecule caused frequent side reactions, and while the route worked in the lab, it was completely irreproducible at 10-to-100-gram scale. Drawing on a steroid chemistry platform built over a decade (10,000+ steroid molecules synthesized, 20+ chiral-center construction methods), the RCS team accurately identified critical reactive sites and designed a new route: seven steps reduced to three, overall yield more than doubled, validated in a single run at tens-of-grams scale.",
            "Two years later, the client reported repeated failures at kilogram scale and questioned whether the process itself was flawed. Rather than rushing to defend, RCS calmly completed four rounds of systematic validation — 1g x2, 10g x2, 100g x2, and 1000g x2 — all reproducing the original data and confirming process stability and reproducibility better than expected.",
            "During validation, RCS proactively optimized further: introducing continuous processing and direct precipitation, integrating previously complex purification steps into a single operation with direct product precipitation, cutting the 100g production cycle from two weeks to just four days. The client praised: \"It is your outstanding work that made the project simple! This is an excellent achievement.\"",
            "The steroid chemistry platform supports early research from Hit-to-Lead and novel structure development to focused library construction, with delivery spanning milligram to kilogram scale. It integrates with ADC, targeted protein degrader, prodrug and nitrogen mustard molecule design, enabling novel therapeutic modalities built on steroid scaffolds. The client has since voluntarily upgraded to a deep collaboration model, tackling even more challenging steroid molecule syntheses with RCS.",
        ],
    },
    "wuxi-apptec-stapled-peptide": {
        "title": "Breaking the Stapled Peptide Bottleneck: WuXi AppTec's WuXi TIDES Delivers Kilogram-Scale GMP API in 8 Months",
        "summary": "A Phase 2 triple stapled peptide project that stalled at another CDMO was transferred to WuXi AppTec. Through integrated WuXi TIDES execution — in-house UAA supply in 6 weeks, re-engineered RCM lifting crude purity 33%, and a metal-scavenging step cutting residual ruthenium ~75-fold — kilogram-scale GMP API was delivered in 8 months and Phase 2 CTM released in 11.",
        "body": [
            "Peptide therapeutics have become an increasingly important modality, with over 100 peptide drugs now on the market globally. Stapled peptides improve drug-like properties by constraining conformation through macrocyclization such as ring-closing olefin metathesis (RCM), stabilizing the alpha-helical structures central to protein-protein interactions. Yet clinical-scale manufacturing faces CMC challenges — unnatural amino acid (UAA) sourcing, RCM conversion and metal residue control. One biotech's Phase 2 triple stapled peptide suffered low and unstable yield, high catalyst loading and difficult catalyst residue control, while also requiring an ultra-high concentration injectable formulation and timely clinical trial material (CTM) delivery.",
            "After extensive challenges at another CDMO, the molecule was transferred to WuXi AppTec, where the WuXi TIDES team applied an integrated approach. The team developed in-house synthetic routes for two non-commercial UAAs, delivering 25 kg of >99% purity UAA within 6 weeks and removing external supply uncertainty. In parallel, it re-engineered the RCM process — optimizing the solvent system, substrate concentration and catalyst addition strategy — improving conversion under strong conformational constraints, reducing catalyst burden and lifting crude purity by 33%.",
            "For residual-ruthenium control, a pre-column metal-scavenging step before prep-HPLC cut residual ruthenium in the final API by ~75-fold versus the crude, while extending column life and shortening the purification cycle by 30%. Final yield more than doubled and several kilograms of GMP API were delivered within 8 months — a material improvement in both process performance and clinical supply readiness for a complex triple-stapled peptide with sequential RCM and demanding metal-residue control.",
            "Speed also came from parallel CMC execution: analytical method development and validation advanced alongside GMP API scale-up, and the drug product team screened 30+ formulation prototypes within ~5 weeks, achieving a stable injectable peptide solution above 100 mg/mL. With UAA supply, API process optimization, analytical work, formulation and CTM manufacturing advancing without idle time, CTM manufacturing, packaging and release were completed within 3 months, and the overall program — from onboarding to Phase 2 CTM release — took 11 months.",
        ],
    },
    "biodlink-h1-2026": {
        "title": "BioDlink 2026 Interim Results: CDMO Revenue RMB 199M, Up 157% YoY, Now Part of the WuXi XDC Platform",
        "summary": "H1 2026 CDMO revenue reached RMB 199M (+157.0% YoY); cumulative customers totaled 116 (16 overseas); 134 CMC projects with 14 added in H1; first commercial-CDMO order secured for Lepu Biopharma's ADC Meiyouheng®; backlog RMB 391M (+95.5% YoY). WuXi XDC completed its tender on 2026-03-31 and held ~60.67% as of end-June.",
        "body": [
            "BioDlink International (1875.HK) reported its unaudited interim results for the six months ended 30 June 2026 — its first full reporting period since joining the WuXi XDC platform. CDMO revenue reached RMB 199M, up 157.0% year-on-year, with a cumulative customer base of 116 (including 16 overseas), reflecting continued global expansion. Total CMC projects stood at 134, with 14 added in H1; 6 PPQ (Process Performance Qualification) projects were secured cumulatively; and the company won its first commercial-CDMO assignment — a formal commercial manufacturing order for Lepu Biopharma's ADC, Meiyouheng®. Order backlog (signed but unfulfilled) reached RMB 391M, up 95.5% YoY. BioDlink was named an outstanding innovation case in the 2025 White Paper on Innovative Drugs and Supply Chains and was awarded \"Emerging CDMO of the Year\" by IMAPAC.",
            "Acquisition and integration advanced materially: WuXi XDC (2268.HK) completed its voluntary conditional cash offer for BioDlink on 31 March 2026 and, as of 30 June 2026, held approximately 60.67% of the company as controlling shareholder. During the period BioDlink entered continuing connected transaction agreements with WuXi XDC and a connected transaction agreement with WuXi Biologics (2269.HK), deeply integrating into the WuXi XDC ecosystem and sharing its end-to-end ADC R&D and manufacturing capabilities, with smooth post-merger integration progress.",
            "On technology platforms, BioDlink continued to strengthen its proprietary moat: the GL-DisacLink® site-specific glycosylation conjugation platform has supported close to 500 early-stage innovative molecular programs, with its first program completing end-to-end ADC process development, GMP manufacturing and FDA IND submission within four months; the BDKcell® (CHO-K1) cell-line platform paired with in-house BDKMedia™ media enables self-sufficient upstream supply; and the BDKLyo® intelligent lyophilisation modelling platform cuts conventional lyophilisation development timelines by more than 50% using just 1–2 experimental rounds, reducing consumable and energy costs.",
            "Commercial products and global footprint advanced in parallel: Pusintin® (Bevacizumab Injection) has been approved in seven markets (with Syria and Mexico added in H1 2026) and accepted for marketing applications in 29 overseas jurisdictions. The company operates four commercial manufacturing lines with large-scale sterile fill-finish capability, backed by a global GMP-aligned quality system that has earned PMDA accreditation in Japan and supported product approvals across China, Indonesia, Nigeria, Pakistan, Colombia and Bolivia. Guided by \"Quality First, Innovation Driven, Success Together,\" BioDlink will continue to expand in the XDC market leveraging WuXi XDC's dual-site global synergy.",
        ],
    },
    "asymchem-h1-2026-ashare": {
        "title": "Asymchem 2026 Half-Year Report (A-Share): Revenue RMB 3.607B, Up 13.13%; Net Profit RMB 520M, Down 15.71%; Full-Year Guidance +19%–22%",
        "summary": "H1 revenue RMB 3.607B (+13.13% YoY); net profit attributable to shareholders RMB 520M (-15.71%); deduct-non-recurring net profit RMB 525M (-7.30%); operating cash flow RMB 822M (+17.18%); total assets RMB 20.83B, net assets RMB 17.74B; no dividend. Full-year 2026 revenue guided to grow 19%–22%.",
        "body": [
            "On 24 August 2026, Asymchem Pharmaceutical Group (Tianjin) Co., Ltd. (002821.SZ / 06821.HK) released its 2026 semi-annual report (A-share). Revenue reached RMB 3.607B, up 13.13% YoY; net profit attributable to shareholders was RMB 520M, down 15.71% YoY; deduct-non-recurring net profit was RMB 525M, down 7.30%. For context, the HK interim report disclosed on 11 August showed H1 revenue of RMB 3.188B and profit of RMB 617M — A-share and HK figures differ slightly due to consolidation scope and accounting presentation, but both reflect steady top-line growth with near-term profit pressure.",
            "Profit quality and balance sheet remained sound: net operating cash flow was RMB 822M, up 17.18% YoY; basic EPS RMB 1.45 (-13.69%); weighted ROE 2.91% (-0.68 ppt); period-end total assets RMB 20.83B (+2.73% vs. prior year-end) and net assets attributable to shareholders RMB 17.74B (+0.59%). The company plans no cash dividend, no bonus shares and no capitalisation of reserves. At period-end the common-shareholder count was 51,711; the largest shareholder ASYMCHEM LABORATORIES, INCORPORATED held 31.91% and HAO HONG held 3.95%, with both controlling shareholder and actual controller unchanged.",
            "On the business front, the company positions itself as a globally leading one-stop CDMO solutions provider. Building on its small-molecule strength, it is advancing chemical macromolecules, biologics, drug product, clinical research services, synthetic biology and new-technology export in concert. With the CDMO sector showing positive momentum in 2026, Asymchem continues to invest heavily in incremental modalities — peptides, oligonucleotides and ADC — consistent with its earlier expansion cadence: chemical macromolecules (peptide/oligonucleotide TIDES) exceeded RMB 1B revenue in 2025 (doubling YoY), and peptide solid-phase capacity is planned to rise from 45,000 L to 69,000 L by end-2026.",
            "Orders and full-year outlook: the company noted that relevant orders typically concentrate in H2 delivery, and therefore guides full-year 2026 revenue to grow 19%–22%. Although Q1 attributable net profit fell 6.82% YoY, Q2 completed a bottom-up inflection. That said, peptide commercial orders have long cycles and uneven revenue recognition, and with overseas customers making up a high share of revenue, geopolitical policy shifts and customer capex cuts remain potential headwinds.",
        ],
    },
    "wuxi-xdc-h1-2026": {
        "title": "WuXi XDC H1 2026: Revenue RMB 3.70B, Up 37.0%; Adjusted Net Profit RMB 1.03B, Up 37.4%",
        "summary": "H1 revenue RMB 3,701.4M (+37.0% AER / +41.5% CER), gross profit RMB 1,371.3M (+40.6%), adjusted net profit attributable to owners RMB 1,027.3M (+37.4%) at a 27.8% margin; 814 global clients, 328 iCMC programs, backlog ~US$2.0B (+50.4%); Singapore XmAb/XBCM3 achieved GMP release in August and BioDlink integration completed.",
        "body": [
            "On August 24, 2026, WuXi XDC Cayman Inc. (2268.HK), a leading global bioconjugate CRDMO, announced its interim results for the six months ended June 30, 2026. Group revenue increased to RMB 3,701.4 million, representing 37.0% year-over-year growth on an actual exchange rate (AER) basis and 41.5% on a constant exchange rate (CER) basis. The growth was primarily driven by continued expansion of the global ADC and broader XDC market, the company's rising share as a leading ADC CRDMO, and the steady advancement of its projects into later stages.",
            "Margins and profitability improved in tandem: gross profit grew 40.6% to RMB 1,371.3 million, with a gross margin of 37.0% (up 0.9 ppts from 2025 1H); adjusted net profit attributable to owners rose 37.4% to RMB 1,027.3 million, with the adjusted margin holding steady at 27.8% (up 0.1 ppt). The improvement reflected gains in operating and manufacturing efficiency, high capacity utilization on strong demand, successful ramp-up of production lines and a higher share of value-added services, together with disciplined SG&A control.",
            "The customer and project base scaled further: the global customer total reached 814, with 15 of the top-20 global pharma companies now engaged; integrated CMC (iCMC) programs totaled 328 (51 newly signed in H1), including 286 integrated ADC and 42 integrated XDC programs. The commercial and PPQ pipeline comprised 2 commercial projects and 21 PPQ programs (2 newly signed in H1). In H1 the Group explored over 3,100 bioconjugate molecules and has cumulatively explored over 22,000 ADC/XDC molecules. Service backlog grew to ~US$2.0B (+50.4% YoY); including potential milestone fees, total backlog reached ~US$2.2B (+62.2% YoY).",
            "The integrated technology platform kept iterating. The clinically validated WuXiDARx™ conjugation platform has advanced 8 ADC pipelines from preclinical to clinical stages, with WuXiDAR4™ enabling 10+ iCMC programs (8 in clinical development). Within WuXi Payload-Linker™, the exatecan-based WuXiTecan-2™ has been applied via licensing to 3 iCMC-stage programs (with Earendil Labs and a European biotech) and pushed the first dual-payload ADC (MMAE + WuXiTecan-2™) from PCC into iCMC development; X-LinC™, a stable conjugation connector, improves in-vivo ADC stability by reducing payload-linker deconjugation.",
            "Capacity and operations expanded: headcount rose to 3,628, with WuXi XDC's standalone workforce over 3,100 and more than 50% holding a master's degree or above; the Group has completed 200+ global client GMP audits, including 27 EU QP audits. The acquisition of BioDlink closed in March 2026, adding capacity and clients; in August the Singapore site's XmAb/XBCM3 achieved GMP release, marking the Group's first manufacturing site outside mainland China, with XDP4 scheduled for GMP release by end-August. Looking ahead, Wuxi will add XDP5/XDP6 drug-product lines and Jiangyin's XPLM2 will secure vertical integration of the critical payload-linker supply chain. The company was named 'Best CDMO' for three consecutive years (2023–2025) at the World ADC Awards and 'Best CRO' in 2025.",
        ],
    },
    "wuxi-biologics-h1-2026": {
        "title": "WuXi Biologics H1 2026: Revenue RMB 11.8B, Up 18.4%; Adjusted Net Profit RMB 3.9B, Up 38.6%",
        "summary": "H1 revenue RMB 11.8B (+18.4% / +23.4% in USD), adjusted gross margin 48.4% (+2.8 ppts), adjusted net profit RMB 3.9B (+38.6%), free cash flow RMB 1.5B (5th year positive); total backlog US$25.1B, 1,064 integrated projects, 68 INDs filed, WuXia™ TrueSite in 70+ programs; BestChrom 51.1% stake sale and global capacity build-out.",
        "source": "WuXi Biologics official WeChat (2026 Interim Results)",
        "source_url": "https://mp.weixin.qq.com/s/QwWUG9Ddona4jLNCAozFKA",
        "body": [
            "On August 25, 2026, WuXi Biologics (2269.HK) announced its 2026 interim results: H1 revenue reached RMB 11.8B, up 18.4% year-over-year (23.4% in USD terms). Despite adverse FX, the adjusted gross margin still improved 2.8 ppts to 48.4%, with IFRS gross margin at 46.2% (+3.5 ppts), as scale effects and higher production efficiency drove profitable growth.",
            "Profitability and cash generation strengthened together: IFRS net profit rose 5.8% to RMB 2.9B, while adjusted net profit grew 38.6% to RMB 3.9B; basic EPS was RMB 0.60 (+3.4%) and adjusted basic EPS RMB 0.81 (+37.3%); EBITDA reached RMB 4.4B (+3.5%) and adjusted EBITDA RMB 5.4B (+24.9%); free cash flow was RMB 1.5B, positive for the 5th consecutive year. At period end, total backlog stood at US$25.1B, including a 3-year backlog of US$5.5B (up ~30% YoY).",
            "Project and 'Win-the-Molecule' momentum was strong: 169 new integrated projects were added in H1 — 123 organic adds (up 43% YoY, a record high) plus 46 contributed by WuXi XDC's BioDlink acquisition — bringing total integrated projects to 1,064, including 78 Phase III and 28 commercial programs, with complex-molecule projects exceeding 50% of the total. Win-the-Molecule added 16 programs in H1 (including 4 Phase III and 1 commercial), 128 cumulative since 2018; the Group completed 68 IND filings in H1, with PPQ runs scheduled at 34 in 2026 and 30 in 2027 at a 100% success rate.",
            "Technology differentiation is converting to commercial edge: WuXia™ TrueSite, launched in October 2025, has already been applied to 70+ programs, shortening DNA-to-IND to six months. Global capacity advanced on multiple fronts: Shanghai Fengxian MFG17 completed its first GMP run, the Chengdu microbial facility was topped out, and the Transcenta Hangzhou site acquisition is planned; in the US, MFG11 (36,000 L) is under construction and MFG18 is being upgraded to commercial; the Singapore DP plant is scheduled for 2027; and the Ireland site secured three major programs. In July 2026 the company signed to sell a 51.1% stake in BestChrom (close expected in December, deconsolidation) to optimize its portfolio.",
            "Talent and quality foundations stayed solid: as of June 30, 2026 the company had 14,705 employees (including 5,180 scientists) with a 98.7% key-talent retention rate; since 2017 it has completed 49 global inspections with no critical deficiencies and operates 15 GMP-certified facilities. WuXi Biologics was named 'Biologics CDMO of the Year 2026' and 'Best Contract Development and Manufacturing Organization 2026'. CEO Dr. Chris Chen noted that broad-based demand growth plus scale effects and efficiency gains drove the profitable expansion, while Chairman Dr. Ge Li emphasized the long-term value of the integrated CRDMO platform.",
        ],
    },
    "porton-cso-zhong": {
        "title": "Porton Appoints Dr. Yongli Zhong as Chief Scientific Officer",
        "summary": "Porton (300363.SZ) announced that Dr. Yongli Zhong, former Principal Scientist at Merck & Co., has joined as Chief Scientific Officer (CSO) to lead innovative process-technology solutions for customers. At Merck for 21 years, Dr. Zhong led process development for multiple innovative drugs from PCC to commercial, with 20+ patents and 90+ papers.",
        "source": "Porton official WeChat",
        "source_url": "https://mp.weixin.qq.com/s/i3004TqKGwvYx_qkt7aRfA",
        "body": [
            "Porton Pharma Solutions Ltd. (300363.SZ) recently announced that Dr. Yongli Zhong has formally joined the company as Chief Scientific Officer (CSO). Dr. Zhong will lead the development of more innovative, competitive-edge technical solutions for customers, leveraging his deep expertise and innovation-driven mindset to strengthen Porton's technological advantages.",
            "Dr. Yongli Zhong graduated from the Sun Yat-sen University Department of Chemistry with both his bachelor's and master's degrees in 1989, then joined the faculty of the Department of Chemistry, staying until the end of 1994. In 1998 he completed his Ph.D. in Organic Chemistry at the Chinese University of Hong Kong, and that same year joined Professor KC Nicolaou's group at The Scripps Research Institute in the US for three years of postdoctoral research on natural-product total synthesis, new organic reactions, and novel methodologies.",
            "After his postdoctoral research, Dr. Zhong joined the Process Research & Development department at Merck & Co. Over his 21 years at Merck, he worked on innovative-drug process development from PCC to commercial production, holding positions of senior scientist, research fellow, and principal scientist. As a creative organic chemist, he led and played a key role in the design, development, and commercialization of many Merck innovative drugs, tackling complex chemical challenges. His output includes 20+ patents, 90+ papers in international journals, and three book chapters.",
            "Oliver Ju, Chairman and CEO of Porton, said: \"I am excited to welcome Dr. Zhong to the Porton team. With over 20 years of distinguished industry experience in innovative-drug process development, Dr. Zhong's arrival will significantly bolster our R&D and technical capabilities. We look forward to his close collaboration with our commercial and delivery teams to tackle critical synthetic-process challenges.\" Dr. Zhong said: \"It is a great honor to join Porton. I am excited to work alongside our team to deliver innovative solutions that support our partners' innovative-drug development journeys and help bring life-changing therapies to patients sooner.\"",
            "Founded in 2005, Porton provides end-to-end CDMO services from pre-clinical to commercial stages, spanning small molecules, TIDES, biologics and conjugates (ADCs, AOCs, DACs, PDCs, RDCs, etc.), and advanced-therapy medicinal products, from drug substance to drug product. As of 2025, Porton has over 4,300 employees globally, has served more than 1,400 customers, and delivered over 5,000 projects.",
        ],
    },
    "insilico-h1-2026": {
        "title": "Insilico Medicine H1 2026: Revenue US$106.3M, Up 287%; First Profitable Half-Year",
        "summary": "Generative-AI drug-discovery company Insilico Medicine (HKEX: 3696) reported H1 2026 results: total revenue US$106.3M (+287.2% YoY), gross margin 90.3%, net profit US$35.54M, adjusted net profit US$51.23M, operating cash flow positive; YTD BD contract value ~US$7.3B with 9 PCC nominations and 8 clinical advancements.",
        "source": "Insilico Medicine official WeChat",
        "source_url": "https://mp.weixin.qq.com/s/rqBlduuXFDIWyZ87h3PMVg",
        "body": [
            "On August 26, 2026, generative-AI-driven clinical-stage drug-discovery company Insilico Medicine (HKEX: 3696) released its 2026 interim results. H1 total revenue reached US$106.3M, up 287.2% year-over-year; gross margin was 90.3%; net profit was US$35.54M and adjusted net profit US$51.23M, marking its first profitable half-year, with operating cash flow turning positive. As of June 30, cash and investment portfolio totaled ~US$584.8M.",
            "By segment, drug-discovery and pipeline revenue was US$103.1M (>300% YoY) and software-solutions revenue ~US$2.70M. Year-to-date, total contract value of out-licensing and R&D partnerships reached ~US$7.3B, validating its 'AI platform + proprietary pipeline + BD monetization' commercialization path.",
            "Global BD partnerships landed densely: in the US/EU, a US$888M oncology collaboration with Servier (US$32M upfront) in January and a US$2.75B license & R&D deal with Eli Lilly (US$115M upfront) in March; in Greater China, US$66M with Hygtia and HK$931M with Qilu in January, a deepened tie with CMS (over RMB 1.2B) in Feb/June, and US$94.75M with Tenacia for CNS in March; in APAC, US$2.5B with SK Biopharmaceuticals in June and ~US$600M with Takeda (≈US$60M initiation) in July.",
            "AI agents and infrastructure kept iterating: Science MMAI Gym (Jan), PandaClaw (Mar), open-source autonomous-lab OS LabClaw (May), and DDD Benchmarks as BaaS (Jul), plus partnerships with Google Cloud and Tencent Health. On the pipeline, 9 PCC nominations and 8 clinical advancements were advanced in H1 — Rentosertib Phase III in China with its inhaler gaining CDE IND; ISM8969/HT-001 securing FDA IND and first-in-human dosing; ISM6331 granted FDA Fast Track, among others.",
            "On capital markets and recognition, 13 brokers now cover the stock; it was included in Stock Connect and the Hang Seng Composite Index on March 9, later entering CSI, FTSE and MSCI Small Cap indices; it earned a Galien Best Startup nomination and ranked #3 on Fast Company's 2026 Most Innovative Biotech list. Insilico demonstrates that generative-AI-driven drug discovery has reached a verifiable commercial closed loop.",
        ],
    },
    "wuxi-xdc-singapore-dp4": {
        "title": "WuXi XDC's Singapore DP4 Facility Achieves GMP Release, Marking First Overseas Drug Product Plant",
        "summary": "WuXi XDC announced GMP release of its first Singapore drug-product facility DP4 for bioconjugates, with annual capacity up to 8 million vials of liquid or lyophilized dosage form. From groundbreaking to GMP release in just 29 months, DP4 is the second capacity facility in Singapore after BCM3.",
        "source": "WuXi XDC official WeChat",
        "source_url": "https://mp.weixin.qq.com/s/hDUXtP0iWijrX_EAb2z_Pg",
        "body": [
            "On August 28, 2026, WuXi XDC Cayman Inc. (\"WuXi XDC\", stock code: 2268.HK), a leading global Contract Research, Development and Manufacturing Organization (CRDMO) focused on bioconjugates, announced that its first drug-product (DP) manufacturing facility DP4 for bioconjugates at its Singapore site has successfully achieved GMP release. This milestone represents not only a further expansion of manufacturing capacity but also a substantive upgrade of WuXi XDC's global supply network, laying a more solid foundation for continuously empowering clients and accelerating the delivery of innovative therapies to patients worldwide.",
            {"img": "/assets/img/wuxi-xdc-singapore-dp4/facility.png", "caption": "DP4 sterile filling line (WuXi XDC Singapore site): one 10 m² + two 30 m² lyophilizers, up to 8 million vials / year (2R / 6R / 10R / 20R / 50R), supporting up to OEB5 high-potency handling"},
            "The DP4 facility is equipped with one 10 m² and two 30 m² lyophilizers, providing annual production capacity of up to 8 million vials of liquid or lyophilized bioconjugates. The facility strictly adheres to GMP standards set by the US FDA, EMA and Singapore HSA, ensuring full-process compliance and product quality control throughout the entire manufacturing workflow.",
            "The facility offers comprehensive end-to-end sterile drug-product manufacturing and packaging services covering washing and sterilization, compounding, vial washing, depyrogenation, filling, lyophilization, capping, external washing, manual and automated visual inspection, labeling and packaging. The core filling line is equipped with a state-of-the-art sterile isolator enabling 100% in-line filling-weight checking and vacuum-free stoppering technology, with filling speed up to 300 vials per minute and a camera-based vision system that performs real-time rejection of vials with missing or high-seated stoppers.",
            "The lyophilizers employ liquid-nitrogen cooling technology with fully automated loading and unloading systems. The automated visual-inspection machine incorporates multi-color imaging, headspace oxygen detection and pulsed X-ray technology. The line is also equipped with semi-automated PUPSIT filtration, AGV automated transfer and fully automated material disinfection devices. The automated packaging line integrates single-vial and multi-vial formats for both commercial and clinical production needs, with labeling, cartoning, secondary packaging and drug traceability functions.",
            "Built to the highest international standards, DP4 features a unique modular facility design with unidirectional flow, advanced high-potency sterile equipment, strict risk classification management, innovative single-use technologies with a comprehensive environmental monitoring system, and fully automated material transfer and disinfection systems — supporting both liquid and lyophilized sterile bioconjugates from clinical to commercial manufacturing. As WuXi XDC's first overseas drug-product facility, DP4 completed the entire process from facility construction, commissioning and qualification, aseptic processing simulation to GMP release in just 29 months — again demonstrating the 'WuXi speed'.",
            "The on-schedule GMP release of DP4 marks the second production-capacity addition at the Singapore site, following the GMP release of the BCM3 facility in mid-August. With this milestone, Singapore can now offer end-to-end services across antibodies, bioconjugate drug substances and drug products. As the first overseas site in WuXi XDC's global network, the company is fully confident in its long-term growth and will continue to accelerate the discovery, development and manufacturing of bioconjugates worldwide through its integrated CRDMO platform — empowering global partners with more resilient supply networks and globally unified quality standards.",
        ],
    },
}

COMPANIES_EN = {
    "wuxi-apptec": {
        "tagline": "Integrated Small-Molecule CRDMO Platform",
        "desc": "A global leading pharmaceutical R&D and manufacturing platform spanning Chemistry, Testing and Biology businesses. Its unique CRDMO model connects drug discovery through commercial manufacturing. H1 2026 revenue was RMB 28.9B with a RMB 66.4B backlog.",
    },
    "wuxi-biologics": {
        "tagline": "Global Large-Molecule CRDMO Leader",
        "desc": "A global leading large-molecule CRDMO providing end-to-end services from discovery through manufacturing, with a global network connecting China, the US, Ireland, Germany and Singapore. H1 2026 revenue of RMB 11.8B (+18.4%), adjusted net profit of RMB 3.9B (+38.6%), with 1,064 integrated projects; hit its 1,000th integrated project milestone in July 2026.",
    },
    "wuxi-xdc": {
        "tagline": "ADC / Bioconjugate CRDMO",
        "desc": "The global leading bioconjugate CRDMO with a one-stop ADC development and manufacturing platform. H1 2026 revenue of RMB 3.70B (+37.0% AER) with adjusted net profit attributable to owners of RMB 1.03B (+37.4%), 814 global clients and 328 iCMC programs; the Singapore BCM3 line completed GMP release in August 2026.",
    },
    "pharmaron": {
        "tagline": "Multi-Modality R&D & Manufacturing Services",
        "desc": "An international life-science services company with an end-to-end platform spanning drug discovery, preclinical and clinical development across small molecules, large molecules and cell & gene therapy. Operating in China, the US and the UK with 27,000+ employees.",
    },
    "asymchem": {
        "tagline": "Small-Molecule CDMO + Emerging Modalities",
        "desc": "A global, technology-driven one-stop CDMO serving 1,100+ clients worldwide. Small molecules remain the core while chemical macromolecules (peptides/oligonucleotides, TIDES) enter rapid monetization — peptide capacity will reach 69,000 L by end-2026.",
    },
    "porton": {
        "tagline": "Small-Molecule API + CGT + New Molecules",
        "desc": "A leading small-molecule API CDMO. Subsidiary Porton Bio focuses on CGT CDMO with an end-to-end platform covering plasmids, viral vectors and cell therapies, and obtained its Drug Manufacturing License (C) in August 2026 to enter commercial-stage manufacturing. That same month, Dr. Yongli Zhong, former Merck Principal Scientist, joined as CSO to strengthen process-technology innovation.",
    },
    "samsung-biologics": {
        "tagline": "World's Largest mAb CDMO",
        "desc": "The world's largest-capacity mAb CDMO with 845,000 L total capacity (including the US Rockville site), rising to 1.325M L at Songdo once Bio Campus II is complete. Accelerating multi-modality expansion in peptides (PolyPeptide acquisition) and ADCs.",
    },
    "lonza": {
        "tagline": "One of the World's Largest CDMOs",
        "desc": "A Swiss-headquartered global CDMO giant spanning biologics, advanced synthesis (small molecules/bioconjugates), drug product and cell & gene therapy. Built end-to-end ADC capability on the integrated Synaffix platform, with ongoing expansion in Visp, Stein and Vacaville.",
    },
    "biodlink": {
        "tagline": "Biologics & ADC/XDC CDMO",
        "desc": "A controlled subsidiary of WuXi XDC, BioDlink is a global biologics and bioconjugate (ADC/XDC) CDMO providing end-to-end services from early R&D through commercial manufacturing. Built on an integrated one-base platform and proprietary technologies such as GL-DisacLink®, BDKcell® and BDKLyo®, it operates four commercial manufacturing lines with large-scale sterile fill-finish capability, backed by a global GMP-aligned quality system accredited by Japan's PMDA. H1 2026 CDMO revenue reached RMB 199M, up 157% YoY.",
    },
    "insilico": {
        "tagline": "Generative-AI-driven Drug Discovery",
        "desc": "A clinical-stage generative-AI-driven drug-discovery company (HKEX: 3696) that applies its AI platform from target discovery through clinical candidates and monetizes via out-licensing and R&D partnerships. H1 2026 revenue reached US$106.3M (+287.2%) with its first profitable half-year; YTD BD contract value reached ~US$7.3B.",
    },
}
